apiVersion: v1
kind: Service
metadata:
  name: devhub-nginx-service
  namespace: my-devhub-nginx-app # Use your project name
  labels:
    app: devhub-nginx # Service labels should match deployment selector
spec:
  selector:
    app: devhub-nginx # Selects pods with this label
  ports:
    - protocol: TCP
      port: 80 # External service port (e.g., for routing or other services in cluster)
      targetPort: 8080 # Internal port the Nginx container is listening on
      name: http
  type: ClusterIP # Internal cluster service. For external access, you'll create a Route later.